### ISSUE TITLE
Gender -- perhaps a bad example for this lecture

### ISSUE THREAD

**Issue by walwoodr** [learn-co-curriculum/intro-to-object-orientation-ruby#5]
With awareness that the examples in the lecture were most likely off the cuff, using "gender" as an example of a variable that is set at birth and cannot be changed is counter-factual, problematic and may make the course exclusionary to non-binary and trans people. I'm not going to drop a block of text, but probably what Avi means to be talking about is Sex rather than gender, especially considering that dogs don't have gender (gender is a social construct that really only applies to humans. female != woman/girl/lady, male != man/dude/guy). Anyway, I'd suggest considering replacing this with a different variable in this example. Birthdate was used on a prior video. ;-)

**Comment by curiositypaths** [comment]
Hi @walwoodr
Thank you so much for bringing this to our attention. Not only was our example counter-factual but it's also an accidental departure from our goal of ensuring everyone feels included in the software engineering world. We picked a poor example.

We will ensure that any future material will use metaphors that fully align with our values

As always, thanks for contributing! 💙
